# Generated by Django 5.1.6 on 2025-02-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('tecido', 'Tecido'), ('couro', 'Couro'), ('espuma', 'Espuma'), ('madeira', 'Madeira'), ('mola', 'Mola'), ('algodao', 'Algodão'), ('poliester', 'Poliéster'), ('veludo', 'Veludo'), ('linho', 'Linho'), ('seda', 'Seda')], default='', max_length=255)),
                ('data', models.DateField(auto_now_add=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fornecedor', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
