# Generated by Django 5.1.6 on 2025-02-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='material',
            new_name='produto',
        ),
    ]
