# Generated by Django 5.1.6 on 2025-03-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
